name: xray-feature-disentanglement
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit=11.0
  - imageio
  - ipykernel
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pillow
  - pip
  - python
  - scikit-image
  - scikit-learn
  - openpyxl
  - pip:
    - pydicom
    - parse
    - umap-learn
    - tensorflow==1.15
    - git+https://github.com/mlmed/torchxrayvision.git@b274a7a32c462faff6df8cde711498d34f1acc36 # install torchxrayvision at the specific commit we used
